In [1]:
import numpy as np

In [2]:
lst=[1,2,3]

In [4]:
np_array=np.array(lst)
print(np_array)
print(type(np_array))

[1 2 3]
<class 'numpy.ndarray'>


In [20]:
lst1=[[1,2,3,9],[4,5,6,9],[7,8,0,9]]
lst1_array=np.array(lst1)
print(lst1_array)
type(lst1_array)

#to check the shape(dimensions) of thr array
print(lst1_array.shape)

#to change the dimensions of lst1_array
lst1_array=np.reshape(lst1_array,(4,3))
print(lst1_array)
print(lst1_array.shape)


[[1 2 3 9]
 [4 5 6 9]
 [7 8 0 9]]
(3, 4)
[[1 2 3]
 [9 4 5]
 [6 9 7]
 [8 0 9]]
(4, 3)


In [24]:
#creating numpy array

#creating with all elements '0'
print(np.zeros((5,5),dtype=int))

#creating with all elements '1'
print(np.ones((5,5),dtype=float))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
#generate random numbers

rand=np.random.randint(10,200)#print random numbers between 10 to 200
print(rand)

np.linspace(2,10,5)#Return evenly spaced numbers over a specified interval
                   #prints evenly spaced 5 numbers between 2 to 10

np.mean(np.linspace(2,10,5))#tells the mean

np.sqrt(np.linspace(2,10,5))#tells square root of all 5 numbers


#operations to all numbers in the array
array=np.linspace(2,10,7)
print(array)
print("array+2=",array+2)
print("array-2=",array-2)
print("array*2=",array*2)

41
[ 2.          3.33333333  4.66666667  6.          7.33333333  8.66666667
 10.        ]
array+2= [ 4.          5.33333333  6.66666667  8.          9.33333333 10.66666667
 12.        ]
array-2= [0.         1.33333333 2.66666667 4.         5.33333333 6.66666667
 8.        ]
array*2= [ 4.          6.66666667  9.33333333 12.         14.66666667 17.33333333
 20.        ]
